Feat/googleps04-93-Add Support for LIST
ollionorg/dynamodb-adapter-fork pull request #6
Opened 2024-12-16 03:48 UTC by nikitajain1998

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

2024-12-18 12:20 UTC, taherkl requested changes

2024-12-18 12:20 UTC, taherkl commented on api/v1/condition.go
> +	matches := regexp.MustCompile(`list_append\((.*?),\s*(.*?)\)`).FindStringSubmatch(operation)
Move the MustCompile at the global level

2024-12-18 12:20 UTC, taherkl commented on service/services/services.go
> +func parseListRemoveTarget(target string) (string, int) {
Add comments

2025-01-13 23:15 UTC, TanmayVartak commented on api/v1/condition.go
> +func parseActionValue(actionValue string, updateAtrr models.UpdateAttr, assignment bool, oldRes map[string]interface{}) (map[string]interface{}, *models.UpdateExpressionCondition) {
Can you add a comment here with examples for actionValue string for better redability?

2025-01-13 23:15 UTC, TanmayVartak commented on api/v1/condition.go
> +			if strings.Contains(field, "[") && strings.Contains(field, "]") {
You don't need this check,. Inside check at line 155 with regex will fail unless field value is like `something[2]`

2025-01-13 23:15 UTC, TanmayVartak commented on api/v1/condition.go
> +				re := regexp.MustCompile(`(\w+)\[(\d+)\]`)
We can do static initialization of this regex outside to avoid compiling this for each query / row. Same for other regex below.

2025-01-13 23:15 UTC, TanmayVartak commented on api/v1/condition.go
> +	matches := regexp.MustCompile(`list_append\((.*?),\s*(.*?)\)`).FindStringSubmatch(operation)
+1

2025-01-17 04:21 UTC, nikitajain1998 commented on api/v1/condition.go
> +	matches := regexp.MustCompile(`list_append\((.*?),\s*(.*?)\)`).FindStringSubmatch(operation)
done

2025-01-17 04:21 UTC, nikitajain1998 commented on service/services/services.go
> +func parseListRemoveTarget(target string) (string, int) {
done

2025-01-17 04:22 UTC, nikitajain1998 commented on api/v1/condition.go
> +func parseActionValue(actionValue string, updateAtrr models.UpdateAttr, assignment bool, oldRes map[string]interface{}) (map[string]interface{}, *models.UpdateExpressionCondition) {
added comments

2025-01-17 04:22 UTC, nikitajain1998 commented on api/v1/condition.go
> +			if strings.Contains(field, "[") && strings.Contains(field, "]") {
updated

2025-01-17 04:22 UTC, nikitajain1998 commented on api/v1/condition.go
> +				re := regexp.MustCompile(`(\w+)\[(\d+)\]`)
updated accordingly

2025-01-20 12:04 UTC, taherkl requested changes

2025-01-20 12:04 UTC, taherkl commented on service/services/services.go
> +	re := regexp.MustCompile(`(.*)\[(\d+)\]`)
Move the MustCompile at global level

2025-01-20 12:04 UTC, taherkl commented on api/v1/condition.go
> +	reListAppend := regexp.MustCompile(`(?i)list_append\(([^)]+),\s*(:\w+)\)`)
Move the MustCompile at global level

2025-01-21 04:43 UTC, nikitajain1998 commented on service/services/services.go
> +	re := regexp.MustCompile(`(.*)\[(\d+)\]`)
done

2025-01-21 04:44 UTC, nikitajain1998 commented on api/v1/condition.go
> +	reListAppend := regexp.MustCompile(`(?i)list_append\(([^)]+),\s*(:\w+)\)`)
done

2025-01-24 05:04 UTC, TanmayVartak commented on api/v1/condition.go
> +				if index < 0 || index >= len(oldList) {
It's possible that `SET list[i] =value` is appending an element to existing list where len(oldlist) = i

2025-01-24 05:04 UTC, TanmayVartak commented on api/v1/condition.go
> +		if len(v) < 2 {
what are the implications of ignoring value?

2025-01-24 05:04 UTC, TanmayVartak commented on api/v1/condition.go
> +				resp[listField] = updatedList
on sucessful assignment previous code is setting status = true

2025-02-10 07:22 UTC, nikitajain1998 commented on api/v1/condition.go
> +				if index < 0 || index >= len(oldList) {
updated

2025-02-10 07:23 UTC, nikitajain1998 commented on api/v1/condition.go
> +				resp[listField] = updatedList
it stores the numeric value status to be added or subtracted

2025-02-10 07:23 UTC, nikitajain1998 commented on api/v1/condition.go
> +		if len(v) < 2 {
This condition ensures that the parsed actionValue contains a valid key-value pair before proceeding. It prevents potential errors caused by incomplete or incorrect parsing.

2025-02-11 13:39 UTC, taherkl approved these changes

2025-02-11 13:42 UTC, merged